# Generated by Django 4.0.3 on 2022-05-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_url_news_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
